services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

  backend:
    build: ./backend
    image: f1-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend

  etl:
    image: f1-etl
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend