name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: f1_dashboard
        ports:
          - 3307:3307
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Build Backend
        working-directory: ./backend
        run: |
          docker build -t f1-backend .

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build